#!/bin/bash

#lab_homes=/srv/lab_homes
lab_homes="$PWD"/lab_homes
share="$PWD"/share

# Generate any missing SSH keys
(cd secrets && ./genkeys)

start_host() (
USERNAME=$1
HOST=$2
PWHASH=$3
GROUP=$4
# --mount type=volume,source="${USERNAME}_data",destination=/data,volume-label=lab.user="$USERNAME" \
# Pre-create the user's home-dir if it doesn't already exist

if [[ $GROUP == 'staff' ]]
then
  permission=''
else
  permission=':ro'
fi

test -d "$lab_homes/$USERNAME" || docker run \
  --rm \
  --volume "$lab_homes:/data/home" \
  --env PWHASH="$PWHASH" \
  --env-file secrets/keys/"$USERNAME".env \
  mattcen/student true
# Start their main container
docker run \
  -d \
  --name "$USERNAME" \
  --volume "$lab_homes/$USERNAME:/data/home/$USERNAME" \
  --volume "$PWD/.cache/vscode_bin:/data/home/$USERNAME/.vscode-server/bin" \
  --volume "$PWD/.cache/pip:/data/home/$USERNAME/.cache/pip" \
  --volume "$PWD/share:/data/home/$USERNAME/code/share${permission}" \
  --network lab \
  --hostname "$HOST" \
  --env PWHASH="$PWHASH" \
  --env-file secrets/keys/"$USERNAME".env \
  --label "lab.user=$USERNAME" \
  --label "traefik.enable=true" \
  --label "traefik.http.routers.$USERNAME.rule=Host(\`$USERNAME.scouthack\`)" \
  --label "traefik.http.routers.$USERNAME.entryPoints=web" \
  --label "traefik.http.routers.$USERNAME.service=$USERNAME" \
  --label "traefik.http.services.$USERNAME.loadbalancer.server.port=80" \
  --label "traefik.http.services.$USERNAME.loadbalancer.sticky=true" \
  --label "sshpiper.username=$USERNAME" \
  --label "sshpiper.container_username=$USERNAME" \
  --label "sshpiper.port=22" \
  --restart unless-stopped \
  mattcen/student
  #--label "sshpiper.authorized_keys=$(cat secrets/keys/$USERNAME.pub 2>/dev/null || :)" \
  #--label "sshpiper.private_key=$(cat secrets/keys/$USERNAME)" \
)

start_all_hosts(){
while IFS=\| read -r user hostname password group
do
  hash=$(docker run --rm alpine mkpasswd "$password")
  echo "Start host $hostname for user $user"
  start_host "$user" "$hostname" "$hash" "$group"
done < <(grep -Ev "^[[:space:]]*(#|$)" secrets/users.psv)
}

#start_host alice h1234
#start_host "$@"
start_all_hosts
