#!/bin/bash

#lab_homes=/srv/lab_homes
lab_homes="$PWD"/lab_homes

start_host() (
USERNAME=$1
HOST=$2
PWHASH=$3
# --mount type=volume,source="${USERNAME}_data",destination=/data,volume-label=lab.user="$USERNAME" \
docker run \
  -d \
  --name "$USERNAME" \
  --volume "$lab_homes/$USERNAME:/data/home/$USERNAME" \
  --network lab \
  --hostname "$HOST" \
  --env PWHASH="$PWHASH" \
  --env-file secrets/keys/"$USERNAME".env \
  --label "lab.user=$USERNAME" \
  --label "traefik.http.routers.$USERNAME.rule=Host(\`$USERNAME.scouthack\`)" \
  --label "traefik.http.services.$USERNAME.loadbalancer.server.port=80" \
  --restart unless-stopped \
  mattcen/student
)

start_all_hosts(){
while IFS=\| read -r user hostname password
do
  hash=$(docker run --rm alpine mkpasswd "$password")
  echo "Start host $hostname for user $user"
  start_host "$user" "$hostname" "$hash"
  install -m 755 -d sshpiper/"$user"
  printf "$user@$user:22" > sshpiper/"$user"/sshpiper_upstream
  chmod 600 sshpiper/"$user"/sshpiper_upstream
done < secrets/users.psv
}

#start_host alice h1234
#start_host "$@"
start_all_hosts
