version: '3'

services:

  sshbase:
    image: mattcen/sshbase
    build:
      context: .
      target: sshbase

  sshprivileged:
    image: mattcen/sshprivileged
    build:
      context: .
      target: sshprivileged

  student:
    image: mattcen/student
    build:
      context: .
      target: student
