#!/bin/bash

mkdir -p keys
while IFS=\| read user hostname _
do
  ssh-keygen -t ed25519 -q -f keys/"$user" -N '' -C "$user"
  printf 'USERNAME=%s\nAUTHORIZED_KEYS=%s\nHOSTNAME=%s\n' \
    "$user" "$(cat keys/"$user".pub)" "$hostname" > keys/"$user".env
done < users.psv
chmod 600 keys/*.pub
