#!/bin/bash

while IFS=\| read user _
do
  ssh-keygen -q -f keys/"$user" -N '' -C "$user"
  printf 'CONTAINER_USER=%s\nAUTHORIZED_KEYS="%s"\n' "$user" "$(cat keys/"$user".pub)" > keys/"$user".env
done < users.psv
chmod 600 keys/*.pub
